version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      MONGO_URI: "${MONGO_URI}" 
      POSTGRES_URI: "${POSTGRES_URI}" 
      KAFKA_SERVER: "${KAFKA_SERVER}"
      KAFKA_SECURITY_PROTOCOL: "${KAFKA_SECURITY_PROTOCOL}"
      KAFKA_SASL_MECHANISM: "${KAFKA_SASL_MECHANISM}"
      KAFKA_USERNAME: "${KAFKA_USERNAME}"
      KAFKA_PASSWORD: "${KAFKA_PASSWORD}"
      KAFKA_TOPIC: "${KAFKA_TOPIC}"
